'use strict';
const faker = require('faker')

module.exports = {
  up: (queryInterface, Sequelize) => {
    const seedSites = (num) => {
      let i = 0;
      let campsites = ["https://thumbs.dreamstime.com/b/travel-trailer-rv-camping-campground-pickup-vacation-summer-62617458.jpg","https://thumbs.dreamstime.com/b/camping-alaska-i-took-picture-northern-lights-below-miles-down-denali-hwy-cantwell-78121574.jpg","https://thumbs.dreamstime.com/b/desert-camping-airstream-mountains-distance-remote-boondocking-dry-blm-location-borrego-springs-california-129307650.jpg","https://thumbs.dreamstime.com/b/luxury-tent-campsite-sunset-full-bed-rugs-perfect-glamping-glamping-tent-site-desert-sunset-183897073.jpg","https://thumbs.dreamstime.com/b/glamping-lifestyle-boiling-kettle-steam-near-big-retro-camping-tent-luxury-travel-accomodation-forest-133376071.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128601.jpg","https://thumbs.dreamstime.com/b/lovely-romantic-glamping-two-wild-seashore-unique-way-to-celebrate-your-love-romantic-camping-trip-two-116285011.jpg","https://thumbs.dreamstime.com/b/luxury-accommodation-glamping-chile-south-modern-tent-national-park-torres-del-paine-chilenian-patagonia-158939546.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128751.jpg","https://thumbs.dreamstime.com/b/glamping-cabin-woods-campsite-canvas-tent-fully-furnished-fire-pit-picnic-area-forest-64927468.jpg","https://thumbs.dreamstime.com/b/glamping-bali-beach-bubble-house-transparent-walls-white-wooden-double-bed-mosquito-net-inside-honeymoon-inflatable-173033747.jpg"]
      let sitesArr = [];
      while(i < num){
        const site = {       
            userId: 1,
            address: faker.address.streetAddress(),
            city: faker.address.city(),
            state: faker.address.state(),
            country: faker.address.country(),
            name: faker.address.streetName(),
            price: faker.commerce.price(50, 500),
            description: faker.fake('{{random.arrayElement(["Come visit our spot off the grid!", "Use our place as a base camp and explore the region", "Ecological campsite in the heart of the forest a paradise for hikers and nature lovers.", "Whether you are looking for a romantic getaway or rest and relaxation,  look no further."])}}'),
            // images: ["https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,g_auto,h_480,q_60,w_720/v1614474638/campground-photos/v6qtjyvobzru4p6r4rl6.jpg","https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,g_auto,h_480,q_60,w_720/v1561310643/campground-photos/b00npespdukz3ibajdev.jpg","https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,g_auto,h_480,q_60,w_720/v1593662531/campground-photos/g8sxi55ewjm7db1wznff.jpg","https://hipcamp-res.cloudinary.com/images/c_limit,f_auto,h_1200,q_60,w_1920/v1629606250/campground-photos/uq2drjc46hl88hjkr3s4/nature-camp-cabin-and-farm-nature-camp-pacific-northwest.jpg"],
            images: [faker.fake('{{random.arrayElement(["https://thumbs.dreamstime.com/b/travel-trailer-rv-camping-campground-pickup-vacation-summer-62617458.jpg","https://thumbs.dreamstime.com/b/camping-alaska-i-took-picture-northern-lights-below-miles-down-denali-hwy-cantwell-78121574.jpg","https://thumbs.dreamstime.com/b/desert-camping-airstream-mountains-distance-remote-boondocking-dry-blm-location-borrego-springs-california-129307650.jpg","https://thumbs.dreamstime.com/b/luxury-tent-campsite-sunset-full-bed-rugs-perfect-glamping-glamping-tent-site-desert-sunset-183897073.jpg","https://thumbs.dreamstime.com/b/glamping-lifestyle-boiling-kettle-steam-near-big-retro-camping-tent-luxury-travel-accomodation-forest-133376071.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128601.jpg","https://thumbs.dreamstime.com/b/lovely-romantic-glamping-two-wild-seashore-unique-way-to-celebrate-your-love-romantic-camping-trip-two-116285011.jpg","https://thumbs.dreamstime.com/b/luxury-accommodation-glamping-chile-south-modern-tent-national-park-torres-del-paine-chilenian-patagonia-158939546.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128751.jpg","https://thumbs.dreamstime.com/b/glamping-cabin-woods-campsite-canvas-tent-fully-furnished-fire-pit-picnic-area-forest-64927468.jpg","https://thumbs.dreamstime.com/b/glamping-bali-beach-bubble-house-transparent-walls-white-wooden-double-bed-mosquito-net-inside-honeymoon-inflatable-173033747.jpg"])}}'), 
            faker.fake('{{random.arrayElement(["https://thumbs.dreamstime.com/b/travel-trailer-rv-camping-campground-pickup-vacation-summer-62617458.jpg","https://thumbs.dreamstime.com/b/camping-alaska-i-took-picture-northern-lights-below-miles-down-denali-hwy-cantwell-78121574.jpg","https://thumbs.dreamstime.com/b/desert-camping-airstream-mountains-distance-remote-boondocking-dry-blm-location-borrego-springs-california-129307650.jpg","https://thumbs.dreamstime.com/b/luxury-tent-campsite-sunset-full-bed-rugs-perfect-glamping-glamping-tent-site-desert-sunset-183897073.jpg","https://thumbs.dreamstime.com/b/glamping-lifestyle-boiling-kettle-steam-near-big-retro-camping-tent-luxury-travel-accomodation-forest-133376071.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128601.jpg","https://thumbs.dreamstime.com/b/lovely-romantic-glamping-two-wild-seashore-unique-way-to-celebrate-your-love-romantic-camping-trip-two-116285011.jpg","https://thumbs.dreamstime.com/b/luxury-accommodation-glamping-chile-south-modern-tent-national-park-torres-del-paine-chilenian-patagonia-158939546.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128751.jpg","https://thumbs.dreamstime.com/b/glamping-cabin-woods-campsite-canvas-tent-fully-furnished-fire-pit-picnic-area-forest-64927468.jpg","https://thumbs.dreamstime.com/b/glamping-bali-beach-bubble-house-transparent-walls-white-wooden-double-bed-mosquito-net-inside-honeymoon-inflatable-173033747.jpg"])}}'),
            faker.fake('{{random.arrayElement(["https://thumbs.dreamstime.com/b/travel-trailer-rv-camping-campground-pickup-vacation-summer-62617458.jpg","https://thumbs.dreamstime.com/b/camping-alaska-i-took-picture-northern-lights-below-miles-down-denali-hwy-cantwell-78121574.jpg","https://thumbs.dreamstime.com/b/desert-camping-airstream-mountains-distance-remote-boondocking-dry-blm-location-borrego-springs-california-129307650.jpg","https://thumbs.dreamstime.com/b/luxury-tent-campsite-sunset-full-bed-rugs-perfect-glamping-glamping-tent-site-desert-sunset-183897073.jpg","https://thumbs.dreamstime.com/b/glamping-lifestyle-boiling-kettle-steam-near-big-retro-camping-tent-luxury-travel-accomodation-forest-133376071.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128601.jpg","https://thumbs.dreamstime.com/b/lovely-romantic-glamping-two-wild-seashore-unique-way-to-celebrate-your-love-romantic-camping-trip-two-116285011.jpg","https://thumbs.dreamstime.com/b/luxury-accommodation-glamping-chile-south-modern-tent-national-park-torres-del-paine-chilenian-patagonia-158939546.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128751.jpg","https://thumbs.dreamstime.com/b/glamping-cabin-woods-campsite-canvas-tent-fully-furnished-fire-pit-picnic-area-forest-64927468.jpg","https://thumbs.dreamstime.com/b/glamping-bali-beach-bubble-house-transparent-walls-white-wooden-double-bed-mosquito-net-inside-honeymoon-inflatable-173033747.jpg"])}}'),
            faker.fake('{{random.arrayElement(["https://thumbs.dreamstime.com/b/travel-trailer-rv-camping-campground-pickup-vacation-summer-62617458.jpg","https://thumbs.dreamstime.com/b/camping-alaska-i-took-picture-northern-lights-below-miles-down-denali-hwy-cantwell-78121574.jpg","https://thumbs.dreamstime.com/b/desert-camping-airstream-mountains-distance-remote-boondocking-dry-blm-location-borrego-springs-california-129307650.jpg","https://thumbs.dreamstime.com/b/luxury-tent-campsite-sunset-full-bed-rugs-perfect-glamping-glamping-tent-site-desert-sunset-183897073.jpg","https://thumbs.dreamstime.com/b/glamping-lifestyle-boiling-kettle-steam-near-big-retro-camping-tent-luxury-travel-accomodation-forest-133376071.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128601.jpg","https://thumbs.dreamstime.com/b/lovely-romantic-glamping-two-wild-seashore-unique-way-to-celebrate-your-love-romantic-camping-trip-two-116285011.jpg","https://thumbs.dreamstime.com/b/luxury-accommodation-glamping-chile-south-modern-tent-national-park-torres-del-paine-chilenian-patagonia-158939546.jpg","https://thumbs.dreamstime.com/b/jul-kanchanaburi-thailand-luxurious-camping-resort-nature-forest-glamping-vacation-tropical-asian-country-luxurious-camping-122128751.jpg","https://thumbs.dreamstime.com/b/glamping-cabin-woods-campsite-canvas-tent-fully-furnished-fire-pit-picnic-area-forest-64927468.jpg","https://thumbs.dreamstime.com/b/glamping-bali-beach-bubble-house-transparent-walls-white-wooden-double-bed-mosquito-net-inside-honeymoon-inflatable-173033747.jpg"])}}')],
            createdAt: new Date(),
            updatedAt: new Date(),
        }
        sitesArr.push(site)
        i++
      }
      return sitesArr
    }
    return queryInterface.bulkInsert('Sites', seedSites(50), {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Sites', null, {});
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
    */
  }
};
